// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeGc52irf9PIRUP62plxCqNmss1Bpe2ew',
    appId: '1:453165515440:web:d5539cb05061c34feb7175',
    messagingSenderId: '453165515440',
    projectId: 'ninamotor-53934',
    authDomain: 'ninamotor-53934.firebaseapp.com',
    storageBucket: 'ninamotor-53934.firebasestorage.app',
    measurementId: 'G-2H6951H8J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0U1ZdklTBovWrcJVA8FcwSSdOHQpa7d0',
    appId: '1:453165515440:android:bb4f777ca6a9398feb7175',
    messagingSenderId: '453165515440',
    projectId: 'ninamotor-53934',
    storageBucket: 'ninamotor-53934.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzLll556iqwZbhDZpcPiTLE1o4NO1eJNc',
    appId: '1:453165515440:ios:48b088d8309b795feb7175',
    messagingSenderId: '453165515440',
    projectId: 'ninamotor-53934',
    storageBucket: 'ninamotor-53934.firebasestorage.app',
    iosBundleId: 'com.ninamotor.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzLll556iqwZbhDZpcPiTLE1o4NO1eJNc',
    appId: '1:453165515440:ios:0e18c587c2f3627aeb7175',
    messagingSenderId: '453165515440',
    projectId: 'ninamotor-53934',
    storageBucket: 'ninamotor-53934.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeGc52irf9PIRUP62plxCqNmss1Bpe2ew',
    appId: '1:453165515440:web:7a689a8cfc56a994eb7175',
    messagingSenderId: '453165515440',
    projectId: 'ninamotor-53934',
    authDomain: 'ninamotor-53934.firebaseapp.com',
    storageBucket: 'ninamotor-53934.firebasestorage.app',
    measurementId: 'G-CGB4V8MG4Z',
  );
}
