// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv3g6D0LhIggwrLgOCm5qPQq1HVDl-W7o',
    appId: '1:900477324465:web:7f6c64199d8b7db090a690',
    messagingSenderId: '900477324465',
    projectId: 'nina-motor',
    authDomain: 'nina-motor.firebaseapp.com',
    storageBucket: 'nina-motor.firebasestorage.app',
    measurementId: 'G-GDW2TXBPWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-9eVR_rX-s0Vje4_zllwGJFxh48fg9Ns',
    appId: '1:900477324465:android:4dcf2c7717e2805d90a690',
    messagingSenderId: '900477324465',
    projectId: 'nina-motor',
    storageBucket: 'nina-motor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7U-DReA6FA-R6g8bECgAWReVxoXyXTdw',
    appId: '1:900477324465:ios:2a5c804b5752fd1290a690',
    messagingSenderId: '900477324465',
    projectId: 'nina-motor',
    storageBucket: 'nina-motor.firebasestorage.app',
    iosBundleId: 'com.ninamotor.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7U-DReA6FA-R6g8bECgAWReVxoXyXTdw',
    appId: '1:900477324465:ios:17e53b28641032af90a690',
    messagingSenderId: '900477324465',
    projectId: 'nina-motor',
    storageBucket: 'nina-motor.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv3g6D0LhIggwrLgOCm5qPQq1HVDl-W7o',
    appId: '1:900477324465:web:0b240053375493a290a690',
    messagingSenderId: '900477324465',
    projectId: 'nina-motor',
    authDomain: 'nina-motor.firebaseapp.com',
    storageBucket: 'nina-motor.firebasestorage.app',
    measurementId: 'G-68965Q60GF',
  );
}
